### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by MarleyCodes** [WGLab/NanoCaller#3]
Hi there,

I would like to use your tool on plant nanopore data and am encountering an error, I hope you can help me!

Installed via miniconda with commit b0719b72ea64d0ee3ce086ab712b8765f0636e11

CMD:
python NanoCaller/scripts/NanoCaller.py -mode both -chrom 1790 -ref WGS-CM.fasta -bam 09.sorted.filtered.unique.targets.bam -model NanoCaller1 -vcf 09_ctg1790.vcf -cpu 10 --prefix 09

ERROR:
/home/mye/.conda/envs/NanoCaller/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/mye/.conda/envs/NanoCaller/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/mye/.conda/envs/NanoCaller/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/mye/.conda/envs/NanoCaller/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/mye/.conda/envs/NanoCaller/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/mye/.conda/envs/NanoCaller/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/data/interos/mye/tools/nanocaller/NanoCaller/scripts/NanoCaller.py", line 79, in <module>
    snp_vcf=snpCaller.test_model(in_dict, pool)
  File "/data/interos/mye/tools/nanocaller/NanoCaller/scripts/snpCaller.py", line 21, in test_model
    coverage = int(stream.read().rstrip('\n'))/(end-start+1)
ValueError: invalid literal for int() with base 10: ''

**Comment by umahsn** [comment]
It seems like the line above line 21 in snpCaller.py which calculates total number of bases in the chosen region is returning null value, which can be because it did not detect any reads in your specified region.

Can you check whether you get any reads when you run 
`samtools view  09.sorted.filtered.unique.targets.bam 1790 -F 3844`  ?

The flag 3844 only allows primary reads to be used.
