### ISSUE TITLE
Module not found tqtm after install with conda

### ISSUE THREAD

**Issue by RxLoutre** [WGLab/NanoCaller#43]
Hello there !

I have installed NanoCaller with conda (mamba) : 

`mamba install -c bioconda nanocaller`

I install this within its own environnement with no other tool in it.

And then trying to call nanocaller, I get the following error : 

```
Nanocaller --bam myBam.bam --ref my_ref.fasta --cpu 4 --mode snps

NanoCaller command and arguments are saved in the following file: /net/beegfs/cfg/rundata/SequencingProjects/202403-008/analysis/Kavish3x_Flongle/ASC410/sushi/args
Traceback (most recent call last):
  File "/net/beegfs/scratch/rboyer/miniconda3/envs/nanocaller/bin/NanoCaller", line 186, in <module>
    run(args)
  File "/net/beegfs/scratch/rboyer/miniconda3/envs/nanocaller/bin/NanoCaller", line 13, in run
    from nanocaller_src import snpCaller, indelCaller
  File "/net/beegfs/scratch/rboyer/miniconda3/envs/nanocaller/bin/nanocaller_src/snpCaller.py", line 2, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

I find this odd, but as I try to fix the issue by installling the requested package with conda, it shows it is actually already installed.

Any idea of what is going on here ? :) 

Thank you for your help !

Best,

Roxane

**Comment by umahsn** [comment]
Hi Roxane,

The problem could be that the correct python installation is not being used by NanoCaller. Can you activate the nanocaller environment and run the following commands in terminal?

```
echo $PATH
python -c 'import sys; print(sys.executable)'
echo $CONDA_PREFIX
```

Best,
Umair
