### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by pvap3** [WGLab/NanoCaller#9]
Hey i am new in this 
I am trying to run following command:
python3 /home/iob/Documents/test/Assembly/graphmap/NanoCaller/scripts/NanoCaller.py -seq ont -o nanocaller_variants -bam sorted_graphmap_out1.bam -ref NC_012920.1.fasta -chrom 1 -prefix nano

but i am this getting error 

Traceback (most recent call last):
  File "/home/iob/Documents/test/Assembly/graphmap/NanoCaller/scripts/NanoCaller.py", line 210, in <module>
    run(args)
  File "/home/iob/Documents/test/Assembly/graphmap/NanoCaller/scripts/NanoCaller.py", line 11, in run
    import snpCaller, indelCaller
  File "/home/iob/Documents/test/Assembly/graphmap/NanoCaller/scripts/snpCaller.py", line 13, in <module>
    if type(tf.contrib) != type(tf): tf.contrib._warning = None
AttributeError: module 'tensorflow' has no attribute 'contrib'

please suggest any possible solution.
Thanks you for your help.

**Comment by umahsn** [comment]
Hi! Can you tell me what version of tensorflow you are using? The contrib module is deprecated in tensorflow 2.0, so we recommend using tensorflow 1.13.

**Comment by pvap3** [comment]
Hello
Thank you for your response.
I am using tensorflow 2.4.1
